baseURL = 'https://jyk2498.github.io/blog/'
locale = 'en-us'
title = 'The Human Delta'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
